sudo: false
language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
addons:
  chrome: stable
  apt:
    packages:
    - chromium-chromedriver
before_script:
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
